language: c

compiler:
    - gcc

notifications:
    email:
        on_success: never
        on_failure: never
    slack: proyectoscarlos:quyUXvpLXPctdsK53REk5ypl

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install libgtk-3-0 libgtk-3-dev libgtk-3-common

script:
    - cd ./src/Interfaz
    - make all
