language: c

compiler:
    - gcc

notifications:
    email:
        on_success: never
        on_failure: never
    slack: proyectoscarlos:quyUXvpLXPctdsK53REk5ypl

script:
    # Interfaz
    - cd ./proyecto/Interfaz
    - make clean && make
