COMPONENT=MovilAppC
include $(MAKERULES)

PFLAGS += -I$(TOSDIR)/platforms/telosa/chips/s1087
PFLAGS += -I$(TOSDIR)/platforms/telosa/chips/s10871
PFLAGS += -I$(TOSDIR)/platforms/telosa/chips/sht11
PFLAGS += -I$(TOSROOT)/tos/lib/printf
PFLAGS += -DNEW_PRINTF_SEMANTICS